<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.redhat.osl</groupId>
    <artifactId>osl-image-build-artifacts-parent</artifactId>
    <version>9.104.0</version>

    <name>OSL image build artifacts</name>
    <description>Maven project to build a Quarkus App used by OSL images</description>
    <packaging>pom</packaging>

    <organization>
        <name>JBoss by Red Hat</name>
        <url>http://www.jboss.org/</url>
    </organization>

    <licenses>
        <license>
            <name>Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <properties>
        <build.quarkusapp.argument.imagename.devmode>osl-swf-devmode</build.quarkusapp.argument.imagename.devmode>
        <build.quarkusapp.argument.imagename.builder>osl-swf-builder</build.quarkusapp.argument.imagename.builder>
        <build.quarkusapp.argument.quarkusplatform.groupid>io.quarkus.platform</build.quarkusapp.argument.quarkusplatform.groupid>
        <build.quarkusapp.argument.quarkusplatform.version>3.20.2</build.quarkusapp.argument.quarkusplatform.version>
        <!-- Quarkus version and Quarkus Platform version might be different due to rebuilds downstream -->
        <build.quarkusapp.argument.quarkus.version>3.20.2</build.quarkusapp.argument.quarkus.version>
        <build.quarkusapp.argument.kogitoversion>9.104.0</build.quarkusapp.argument.kogitoversion>

        <!-- Start of block of plugins and dependencies that will be given to build-quarkus-app.sh script-->
        <version.maven-resouces-plugin>3.3.1</version.maven-resouces-plugin>
        <version.maven-install-plugin>3.1.4</version.maven-install-plugin>
        <version.maven-jar-plugin>3.4.2</version.maven-jar-plugin>
        <version.maven-clean-plugin>3.5.0</version.maven-clean-plugin>
        <version.maven-deploy-plugin>3.1.4</version.maven-deploy-plugin>
        <version.maven-site-plugin>3.21.0</version.maven-site-plugin>
        <version.maven-compiler-plugin>3.14.0</version.maven-compiler-plugin>
        <version.maven-surefire-plugin>3.5.3</version.maven-surefire-plugin>
        <version.maven-failsafe-plugin>3.5.3</version.maven-failsafe-plugin>
        <version.brotli4j>1.16.0</version.brotli4j> <!-- Needs to be aligned with same version used on quarkus-bom -->

        <gav.maven-resouces-plugin>org.apache.maven.plugins:maven-resources-plugin:${version.maven-resouces-plugin}</gav.maven-resouces-plugin>
        <gav.maven-install-plugin>org.apache.maven.plugins:maven-install-plugin:${version.maven-install-plugin}</gav.maven-install-plugin>
        <gav.maven-jar-plugin>org.apache.maven.plugins:maven-jar-plugin:${version.maven-jar-plugin}</gav.maven-jar-plugin>
        <gav.maven-clean-plugin>org.apache.maven.plugins:maven-clean-plugin:${version.maven-clean-plugin}</gav.maven-clean-plugin>
        <gav.maven-deploy-plugin>org.apache.maven.plugins:maven-deploy-plugin:${version.maven-deploy-plugin}</gav.maven-deploy-plugin>
        <gav.maven-site-plugin>org.apache.maven.plugins:maven-site-plugin:${version.maven-site-plugin}</gav.maven-site-plugin>

        <build.quarkusapp.argument.maven-plugins-gav>${gav.maven-resouces-plugin} ${gav.maven-install-plugin} ${gav.maven-jar-plugin} ${gav.maven-clean-plugin} ${gav.maven-deploy-plugin} ${gav.maven-site-plugin}</build.quarkusapp.argument.maven-plugins-gav>
        <build.quarkusapp.argument.properties-with-versions>compiler-plugin.version:${version.maven-compiler-plugin} surefire-plugin.version:${version.maven-surefire-plugin} failsafe-plugin.version:${version.maven-failsafe-plugin}</build.quarkusapp.argument.properties-with-versions>
        <build.quarkusapp.argument.quarkus-extensions-extra-deps>com.aayushatharva.brotli4j:native-linux-aarch64:${version.brotli4j}</build.quarkusapp.argument.quarkus-extensions-extra-deps>
        <!-- End of block of plugins and dependencies that will be given to build-quarkus-app.sh script-->

        <version.exec-maven-plugin>3.5.1</version.exec-maven-plugin>
        <version.build-helper-maven-plugin>3.6.1</version.build-helper-maven-plugin>
    </properties>

    <modules>
<!--        <module>devmode-quarkus-app</module>-->
<!--        <module>devmode-maven-repo</module>-->
        <module>builder-quarkus-app</module>
        <module>builder-maven-repo</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>${version.exec-maven-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${version.build-helper-maven-plugin}</version>
                </plugin>

                <!-- Start of block of plugins that will be given to build-quarkus-app.sh script-->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${version.maven-resouces-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>${version.maven-install-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${version.maven-jar-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${version.maven-clean-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>${version.maven-deploy-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>${version.maven-site-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${version.maven-compiler-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${version.maven-surefire-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${version.maven-failsafe-plugin}</version>
                </plugin>
                <!-- End of block of plugins that will be given to build-quarkus-app.sh script-->
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <inherited>false</inherited>
                <executions>
<!--                    <execution>-->
<!--                        <id>devmode-quarkus-app</id>-->
<!--                        <phase>compile</phase>-->
<!--                        <goals>-->
<!--                            <goal>exec</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <executable>${project.basedir}/build-quarkus-app.sh</executable>-->
<!--                            <arguments>-->
<!--                                <argument>${build.quarkusapp.argument.imagename.devmode}</argument>-->
<!--                                <argument>${build.quarkusapp.argument.quarkusplatform.groupid}</argument>-->
<!--                                <argument>${build.quarkusapp.argument.quarkusplatform.version}</argument>-->
<!--                                <argument>${build.quarkusapp.argument.kogitoversion}</argument>-->
<!--                                <argument>${build.quarkusapp.argument.maven-plugins-gav}</argument>-->
<!--                                <argument>${build.quarkusapp.argument.properties-with-versions}</argument>-->
<!--                                <argument>${build.quarkusapp.argument.quarkus-extensions-extra-deps}</argument>-->
<!--                                <argument>${build.quarkusapp.argument.quarkus.version}</argument>-->
<!--                            </arguments>-->
<!--                        </configuration>-->
<!--                    </execution>-->
                    <execution>
                        <id>builder-quarkus-app</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>${project.basedir}/build-quarkus-app.sh</executable>
                            <arguments>
                                <argument>${build.quarkusapp.argument.imagename.builder}</argument>
                                <argument>${build.quarkusapp.argument.quarkusplatform.groupid}</argument>
                                <argument>${build.quarkusapp.argument.quarkusplatform.version}</argument>
                                <argument>${build.quarkusapp.argument.kogitoversion}</argument>
                                <argument>${build.quarkusapp.argument.maven-plugins-gav}</argument>
                                <argument>${build.quarkusapp.argument.properties-with-versions}</argument>
                                <argument>${build.quarkusapp.argument.quarkus-extensions-extra-deps}</argument>
                                <argument>${build.quarkusapp.argument.quarkus.version}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>